language: python
group: travis_latest

git:
  depth: 3
  quiet: true

python:
- 3.6
# - 3.7  waiting py37 wheels

os:
- linux

install: pip install -e .[tests]

script: 
- pytest -rsv
- flake8
#  - mypy . --ignore-missing-imports   # need new version of mypy

after_success:
- if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
  pytest --cov;
  coveralls;
  fi

